### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by marjedka** [adrianb11/directadmin_rclone_backup#11]
Warning: Invalid argument supplied for foreach() in /usr/local/directadmin/plugins/rclone_backup/admin/elements/pages/create.php on line 30

![2022-01-13_16-54-51](https://user-images.githubusercontent.com/12069713/149363732-38d28d76-9cd7-4d1f-b4ad-c33444598c77.png)

**Comment by adrianb11** [comment]
New version coming today.  Please update manually and see if the error persists.

**Comment by adrianb11** [comment]
This has been resolved in version 1.0.5

**Comment by FatGrizzly** [comment]
@adrianb11 I am still having this issue on latest version.
DA: Latest
Rclone-Backup: Latest
